from parts_of_speech.univeral_pos import *

UNIVERSAL_TO_DICTIONARY = {
    "ADJ": ADJECTIVE,
    "JJ": ADJECTIVE,
    "JJS": ADJECTIVE,
    "JJR": ADJECTIVE,
    "ADP": ADPOSITION,
    "IN": ADPOSITION,
    "TO": ADPOSITION,
    "ADV": ADVERB,
    "WRB": ADVERB,
    "PRP$": ADVERB,
    "PRP": ADVERB,
    "RB": ADVERB,
    "EX": ADVERB,
    "CONJ": CONJUNCTION,
    "CC": CONJUNCTION,
    "DET": DETERMINER,
    "DT": DETERMINER,
    "NOUN": NOUN,
    "NN": NOUN,
    "NNP": NOUN,
    "NNS": NOUN,
    "NUM": NUMERAL,
    "CD": NUMERAL,
    "PRT": PARTICLE,
    "PRON": PRONOUN,
    "WP": PRONOUN,
    "WP$": PRONOUN,
    "VERB": VERB,
    "VBN": VERB,
    "VBD": VERB,
    "VBZ": VERB,
    "VBG": VERB,
    "VBP": VERB,
    "MD": VERB,
    ".": PUNCTUATION,
    ":": PUNCTUATION,
    "X": OTHER,
}
